//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P.V.WantHelp_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sesiones
    {
        public sesiones()
        {
            this.archivos = new HashSet<archivos>();
            this.archivos1 = new HashSet<archivos>();
            this.mensajes = new HashSet<mensajes>();
            this.mensajes1 = new HashSet<mensajes>();
            this.Respuestas_Chat = new HashSet<Respuestas_Chat>();
            this.Respuestas_Chat1 = new HashSet<Respuestas_Chat>();
        }
    
        public int id { get; set; }
        public string titulo { get; set; }
        public string descriocion { get; set; }
        public int idCu { get; set; }
    
        public virtual ICollection<archivos> archivos { get; set; }
        public virtual ICollection<archivos> archivos1 { get; set; }
        public virtual Cursos Cursos { get; set; }
        public virtual Cursos Cursos1 { get; set; }
        public virtual ICollection<mensajes> mensajes { get; set; }
        public virtual ICollection<mensajes> mensajes1 { get; set; }
        public virtual ICollection<Respuestas_Chat> Respuestas_Chat { get; set; }
        public virtual ICollection<Respuestas_Chat> Respuestas_Chat1 { get; set; }
    }
}
